### ISSUE TITLE
Error on adding library by Gradle

### ISSUE THREAD

**Issue by masoud-c** [quentin7b/android-location-tracker#8]
When add android-location-tracker to my dependencies I get an error:
      Error:Failed to resolve: com.android.support:support-annotations:23.1.1

why is that?

**Comment by qk7b** [comment]
_Android Location Tracker_ has a dependency on `com.android.support:support-annotations:23.1.1`. 
To get more information, please see the [Android website](http://developer.android.com/tools/support-library/features.html#annotations).

Means that in order to use it, you **must** have this library installed within your SDK or with a special _maven_ provider.

You can check the _support library_ and the _support repository_ are installed from your _Android SDK_
<img width="660" alt="support" src="https://cloud.githubusercontent.com/assets/2990298/12141581/eb333eaa-b470-11e5-9e64-f27d9efde9b8.png">

If it is ok then I'll close the issue

**Comment by qk7b** [comment]
Since there is no more discussion. I close this issue
